export const FILTER_SET = 'FILTER_SET';

export const MESSAGES_RECEIVE_ALL = 'MESSAGES_RECEIVE_ALL';
export const MESSAGE_RECEIVE_ONE = 'MESSAGE_RECEIVE_ONE';
export const MESSAGE_DELETE_ONE = 'MESSAGE_DELETE_ONE';
