export default {
  MESSAGES_ADD: 'MESSAGES_ADD',
  MESSAGES_CLEAR: 'MESSAGES_CLEAR',
  MESSAGES_EXPIRE: 'MESSAGES_EXPIRE',

  GAME_RECEIVE_STATE: 'GAME_RECEIVE_STATE',
  GAME_PLAYER_JOIN: 'GAME_PLAYER_JOIN',
  GAME_PLAYER_LEAVE: 'GAME_PLAYER_LEAVE',
};
