export default {
  MESSAGE_GET_ALL_START: 'MESSAGE_GET_ALL_START',
  MESSAGE_GET_ALL_SUCCESS: 'MESSAGE_GET_ALL_SUCCESS',
  MESSAGE_GET_ONE_SUCCESS: 'MESSAGE_GET_ONE_SUCCESS',
  MESSAGE_DELETE_ONE_SUCCESS: 'MESSAGE_DELETE_ONE_SUCCESS',
  MESSAGE_SET_FILTER_LABEL: 'MESSAGE_SET_FILTER_LABEL',

  LABEL_GET_ALL_START: 'LABEL_GET_ALL_START',
  LABEL_GET_ALL_SUCCESS: 'LABEL_GET_ALL_SUCCESS',
  LABEL_GET_ONE_SUCCESS: 'LABEL_GET_ONE_SUCCESS',
};
